<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'productName' => 'Smartphone X12 Pro',
                'description' => 'Smartphone flagship dengan performa tinggi, layar AMOLED 6.7 inci, kamera 108MP, dan baterai 5000mAh.',
                'price'       => 3499000,
                'stock'       => 50,
                'image'       => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Elektronik',
                'rating'      => 4.8,
                'label'       => 'Terlaris',
                'location'    => 'Jakarta',
            ],
            [
                'productName' => 'Kaos Polos Premium',
                'description' => 'Kaos polos berbahan cotton combed 30s, nyaman dipakai sehari-hari, tersedia berbagai warna.',
                'price'       => 89000,
                'stock'       => 200,
                'image'       => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Fashion',
                'rating'      => 4.7,
                'label'       => null,
                'location'    => 'Bandung',
            ],
            [
                'productName' => 'Headphone Wireless',
                'description' => 'Headphone bluetooth dengan noise cancelling aktif, bass yang kuat, dan daya tahan baterai 30 jam.',
                'price'       => 249000,
                'stock'       => 30,
                'image'       => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Elektronik',
                'rating'      => 4.9,
                'label'       => 'Diskon',
                'location'    => 'Surabaya',
            ],
            [
                'productName' => 'Blender Dapur Mini',
                'description' => 'Blender mini multifungsi untuk dapur, kapasitas 1 liter, mudah dibersihkan, daya 300W.',
                'price'       => 179000,
                'stock'       => 75,
                'image'       => 'https://images.unsplash.com/photo-1616628182509-6f4d67dbdcce?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Rumah Tangga',
                'rating'      => 4.6,
                'label'       => null,
                'location'    => 'Malang',
            ],
            [
                'productName' => 'Hoodie Casual Unisex',
                'description' => 'Hoodie kasual unisex berbahan fleece tebal, cocok untuk cuaca dingin, tersedia ukuran S-XXL.',
                'price'       => 155000,
                'stock'       => 120,
                'image'       => 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Fashion',
                'rating'      => 4.8,
                'label'       => null,
                'location'    => 'Yogyakarta',
            ],
            [
                'productName' => 'Brightening Serum 30ml',
                'description' => 'Serum pencerah wajah dengan kandungan Vitamin C dan Niacinamide, cocok untuk semua jenis kulit.',
                'price'       => 129000,
                'stock'       => 90,
                'image'       => 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Kecantikan',
                'rating'      => 4.7,
                'label'       => 'Baru',
                'location'    => 'Bekasi',
            ],
            [
                'productName' => 'Jam Tangan Digital',
                'description' => 'Jam tangan digital sporty dengan fitur stopwatch, alarm, dan tahan air hingga 30 meter.',
                'price'       => 199000,
                'stock'       => 60,
                'image'       => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Aksesoris',
                'rating'      => 4.5,
                'label'       => null,
                'location'    => 'Depok',
            ],
            [
                'productName' => 'Sepatu Sneakers Urban',
                'description' => 'Sneakers urban dengan sol karet tebal, desain modern, cocok untuk aktivitas sehari-hari.',
                'price'       => 329000,
                'stock'       => 45,
                'image'       => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Fashion',
                'rating'      => 4.9,
                'label'       => null,
                'location'    => 'Semarang',
            ],
            [
                'productName' => 'Kopi Bubuk Arabika',
                'description' => 'Kopi arabika asli Aceh, diproses secara natural, aroma kuat dengan cita rasa fruity dan sedikit asam.',
                'price'       => 65000,
                'stock'       => 150,
                'image'       => 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Makanan',
                'rating'      => 4.8,
                'label'       => 'Promo',
                'location'    => 'Aceh',
            ],
            [
                'productName' => 'Tas Selempang Casual',
                'description' => 'Tas selempang kasual berbahan canvas berkualitas, kapasitas besar, cocok untuk pria dan wanita.',
                'price'       => 119000,
                'stock'       => 80,
                'image'       => 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Aksesoris',
                'rating'      => 4.6,
                'label'       => null,
                'location'    => 'Bogor',
            ],
            [
                'productName' => 'Lampu Meja Minimalis',
                'description' => 'Lampu meja desain minimalis dengan cahaya LED hangat, cocok untuk belajar dan bekerja.',
                'price'       => 149000,
                'stock'       => 55,
                'image'       => 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Rumah Tangga',
                'rating'      => 4.7,
                'label'       => null,
                'location'    => 'Solo',
            ],
            [
                'productName' => 'Hydrating Face Mask',
                'description' => 'Masker wajah pelembab dengan kandungan hyaluronic acid dan aloe vera, kulit terasa lembut dan segar.',
                'price'       => 49000,
                'stock'       => 200,
                'image'       => 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Kecantikan',
                'rating'      => 4.5,
                'label'       => null,
                'location'    => 'Tangerang',
            ],
            [
                'productName' => 'Speaker Bluetooth Mini',
                'description' => 'Speaker bluetooth portabel dengan suara jernih, tahan air IPX5, baterai tahan 8 jam.',
                'price'       => 219000,
                'stock'       => 70,
                'image'       => 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Elektronik',
                'rating'      => 4.8,
                'label'       => null,
                'location'    => 'Medan',
            ],
            [
                'productName' => 'Set Alat Masak Premium',
                'description' => 'Set peralatan masak lengkap berbahan stainless steel anti karat, terdiri dari 8 pcs.',
                'price'       => 459000,
                'stock'       => 25,
                'image'       => 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Rumah Tangga',
                'rating'      => 4.9,
                'label'       => null,
                'location'    => 'Makassar',
            ],
            [
                'productName' => 'Dompet Kulit Pria',
                'description' => 'Dompet pria berbahan kulit sintetis premium, desain slim, banyak slot kartu.',
                'price'       => 139000,
                'stock'       => 100,
                'image'       => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Aksesoris',
                'rating'      => 4.6,
                'label'       => null,
                'location'    => 'Palembang',
            ],
            [
                'productName' => 'Keripik Pisang Coklat',
                'description' => 'Keripik pisang berlapis coklat premium, renyah dan manis, oleh-oleh khas Lampung.',
                'price'       => 35000,
                'stock'       => 300,
                'image'       => 'https://images.unsplash.com/photo-1615486363973-2f15ee89f580?auto=format&fit=crop&w=900&q=80',
                'category'    => 'Makanan',
                'rating'      => 4.7,
                'label'       => 'Favorit',
                'location'    => 'Lampung',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
